version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test -- --detectOpenHandles

  trigger_master:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Notify master build trigger
          command: echo "Triggered a build on master due to a successful staging build."

workflows:
  version: 2
  build:
    jobs:
      - staging-build:
          filters:
            branches:
              ignore: master 
      - trigger_master_build:
          requires:
            - staging-build
          filters:
            branches:
              only: staging # This job will run only for the staging branch
