version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run ESLint
          command: npx eslint .

  test:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test -- --detectOpenHandles
      - run:
          name: Run ESLint
          command: npx eslint .

  staging-build:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test -- --detectOpenHandles
      - run:
          name: Run ESLint
          command: npx eslint .

  trigger_master:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - run:
          name: Notify master build trigger
          command: echo "Triggered a build on master due to a successful staging build."

workflows:
  version: 2
  build:
    jobs:
      - lint 
      - staging-build:
          requires:
            - lint
          filters:
            branches:
              ignore: master  
      - trigger_master:
          requires:
            - staging-build
          filters:
            branches:
              only: staging 
